#ifndef EXIT_CODES_H
#define EXIT_CODES_H

typedef enum 
{
	SPARK_EXIT_SUCCESS = 0,
	SPARK_EXIT_GENERAL_ERROR = 1,
	SPARK_EXIT_INVALID_ARGUMENTS = 2,
	SPARK_EXIT_FILE_NOT_FOUND = 10,
	SPARK_EXIT_FILE_READ_FAILURE = 11,
	SPARK_EXIT_PERMISSION_DENIED = 12,
	SPARK_EXIT_OUT_OF_MEMORY = 13,
	SPARK_EXIT_MEMORY_ALLOCATION_ERROR = 14,
	SPARK_EXIT_CONFIGURATION_ERROR = 15,
	SPARK_EXIT_NETWORK_ERROR = 16
} ExitCode;

#endif /* EXIT_CODES_H */
